config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about", to: "about#index", as: :about

  get "sign-up", to: "registrations#new", as: :sign_up

  post "sign-up", to: "registrations#create"

  delete "Logout", to: "sessions#destroy", as: :logout
  get "sign_in", to: "sessions#new", as: :sign_in
  post "sign_in", to: "sessions#create"



  resources :messages, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]
  root to: "main#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/Current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :subject, :body, presence: true
  def sender
    user.email
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Current.user.messages
  end
  def new
    @message = Message.new
  end
  def create
    @message = Current.user.messages.new(message_params)

    if @message.save
      redirect_to messages_path, notice: "Message created successfully."
    else
      render :new, alert: "Message failed to create."
    end
  end
  private
  def message_params
    params.require(:message).permit(:subject, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    byebug
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Signed up!"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end
  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @user= User.find_by(email: params[:email])
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Signed in!"
    else
      flash.now.alert = "Email or password is invalid"
      render :new
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mailing List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex justify-content-center p-5">
<div class="text-center d-flex  flex-column">
    
    <h1> Welcome to the mailing list</h1>
    
<div>
</div>

app/views/messages/index.html.erb
<h1>Your Messages</h1>

<% if @messages.any? %>
    <ul>
        <% @messages.each do |message| %>
            <li>
                <strong>From:</strong> <%= message.sender %><br>
                <strong>Subject:</strong> <%= message.subject %><br>
                <strong>Body:</strong> <%= message.body %><br>
                <strong>Sent at:</strong> <%= message.created_at.strftime("%B %d, %Y %H:%M") %>
            </li>
        <% end %>
    </ul>
<% else %>
    <p>You have no messages.</p>
<% end %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= form_with(model: @message, local: true, html: { class: 'needs-validation', novalidate: true }) do |form| %>
  <% if @message.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
        <% @message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :subjet, class: 'form-label' %>
    <%= form.text_field :subject, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Please provide a title.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control', rows: 5, required: true %>
    <div class="invalid-feedback">
      Please provide content.
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Create Message', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back', messages_path, class: 'btn btn-secondary mt-3' %>

<script>
  // Example starter JavaScript for disabling form submissions if there are invalid fields
  (function () {
    'use strict'

    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.querySelectorAll('.needs-validation')

    // Loop over them and prevent submission
    Array.prototype.slice.call(forms)
      .forEach(function (form) {
        form.addEventListener('submit', function (event) {
          if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
          }

          form.classList.add('was-validated')
        }, false)
      })
  })()
</script>

app/views/shared/_flash.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
</div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
                 <%= link_to 'About', about_path, class:"nav-link" %> 
            </li>
            <%if Current.user %>
                <li class="nav-item">
                    <%= link_to 'Messages', messages_path, class:"nav-link" %> 
                </li>
                <li class="nav-item">
                    <%= link_to 'new message', new_message_path, class:"nav-link" %> 
                </li>
            <% end %>
            
        </ul>
        <ul class="navbar-nav ms-auto">
            <% if Current.user %>
                <li class="nav-item me-2">
                    <p>  <span class="ms-2"><%= Current.user.email %></span></p>
                </li>
                <li class="nav-item">
                    <%= button_to "Log out", logout_path , method: :delete, class: "btn btn-primary" %>
                </li>

            <% else %>
                <li class="nav-item">
                    <%= link_to 'Sign up', sign_up_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign in', sign_in_path, class:"nav-link" %>
                </li>
                
            <% end %>
        </ul>
        </div>
    </div>
</nav>